#ifndef IOCTLCMD_H
#define IOCTLCMD_H

#include <linux/ioctl.h>

/* attribution des numero de commande ioctl */
#define CHARDRIVER_IOC_MAGIC 'j'

#define CHARDRIVER_IOC_GETNUMDATA _IO(CHARDRIVER_IOC_MAGIC,0)
#define CHARDRIVER_IOC_GETNUMREADER _IO(CHARDRIVER_IOC_MAGIC,1)
#define CHARDRIVER_IOC_GETBUFSIZE _IO(CHARDRIVER_IOC_MAGIC,2)
#define CHARDRIVER_IOC_SETBUFSIZE _IOW(CHARDRIVER_IOC_MAGIC,3)

#define CHARDRIVER_IOC_MAXNR 3

#endif // IOCTLCMD_H
